### ISSUE TITLE
Change Discord Channels

### ISSUE THREAD

**Issue by gyroflaw** [gyroflaw/joy-disco-bots#12]
Posts tagged with `manifestos` -> council
general -> forum-bot

Originally posted [here](https://discord.com/channels/933091008529448990/933091008529448993/1074433103642247331)

**Comment by chrlschwb** [comment]
please close this issue if it's handled

**Comment by traumschule** [comment]
Looks [done](https://github.com/gyroflaw/joy-disco-bots/pull/13/files#diff-4080351ad328f01a5cb717a600f0dcdd7a30dc29b74fc1e7d42f7a87a74eed55R281).
